version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db_desafio'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
    volumes:
        - 'postgres:/var/lib/postgresql/data'
    networks:
        - 'app-network'
networks:
    app-network:
        driver: bridge
volumes:
    postgres: